// src/components/Project.vue
<template>
  <div class="project" :style="cssVars">
    <div class="header">
      <h1>{{ info.name }}</h1>
      <span class="lang">{{ info.lang }}</span>
    </div>
    <div class="description">
      <p v-for="d in info.description" :key="d">{{ d }}</p>
    </div>
    <div v-if="info.tags" class="tags">
      <p v-for="t in info.tags" :key="t">{{ t }}</p>
    </div>
    <a v-if="info.url" :href="info.url" class="repo">
      {{ repoLabel(info.url) }}
    </a>
    <p v-else class="norepo">
      Private project
    </p>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from "vue-property-decorator";
import ProjectInfo from "@/lib/ProjectInfo";

@Component
export default class Project extends Vue {
  @Prop({ required: true, type: Object }) readonly info?: ProjectInfo;

  get cssVars() {
    const from = Math.floor(Math.random() * 360);
    const to = from + Math.floor(Math.random() * 30) + 30;

    const deg = Math.floor(Math.random() * 360);

    return {
      "--bg-deg": deg + "deg",
      "--bg-from": "hsl(" + from + ",80%,35%)",
      "--bg-to": "hsl(" + to + ",80%,35%)"
    };
  }

  repoLabel(repoUrl: string) {
    const url = repoUrl.toLowerCase();
    switch (true) {
      case /github/.test(url):
        return "Open on GitHub";
      case /bitbucket/.test(url):
        return "Open on BitBucket";
      case /gitlab/.test(url):
        return "Open on GitLab";
    }
  }
}
</script>

<style scoped lang="scss">
@import "./node_modules/include-media/dist/include-media";

$breakpoints: (
  phone: 320px,
  tablet: 720px,
  desktop: 910px
);

%repotext {
  width: 100%;
  padding: 0.25rem;
  margin: 0;
  border-radius: 0.2rem;

  color: #fff;
  font-size: 1rem;
  font-weight: bold;
  text-decoration: none;
}

.project {
  display: flex;
  flex-direction: column;

  min-height: 15rem;
  flex-basis: 90%;
  flex-grow: 1;
  margin: 1vh 2vh;

  background: linear-gradient(
    var(--bg-deg, 90deg),
    var(--bg-from, #000),
    var(--bg-to, #fff)
  );
  border-radius: 0.2rem;
  color: #fff;

  @include media(">=tablet", "<desktop") {
    flex-basis: 45%;
  }

  @include media(">=desktop") {
    flex-basis: 30%;
  }

  .header {
    display: flex;
    flex-wrap: nowrap;
    justify-content: space-between;
    align-items: center;
    align-content: space-between;

    border-bottom: solid #fff 0.15rem;

    h1 {
      flex-grow: 1;

      color: #fff;
      font-size: 1.5rem;
      font-weight: bold;
      border: none;
      padding-top: 0.5rem;
      padding-left: 0.7rem;
    }

    .lang {
      display: inline;
      position: relative;
      top: 0;
      right: 0;

      padding: 0.1rem 1rem;
      margin: 0 0.5rem;

      background: #fff3;

      border: solid #fff 2px;
      border-radius: 1rem;

      &:hover {
        background: #0002;
      }
    }
  }

  .description {
    flex-grow: 1;
    width: 100;
    padding: 1vh 0.5rem;
  }

  .tags {
    display: flex;
    flex-wrap: wrap;
    padding: 0.1rem;

    border-top: dashed #fff5 1px;

    * {
      padding: 0.25rem;
      margin: 0.1rem;
      border-radius: 0.2rem;

      color: #fff;
      background: #0002;
      font-size: 0.65rem;
      text-decoration: none;
    }
  }

  .repo {
    @extend %repotext;

    background: linear-gradient(45deg, #fff4, #0000);

    &:hover {
      background: linear-gradient(45deg, #fff2, #0000);
    }

    &:active {
      background: #0004;
    }
  }

  .norepo {
    @extend %repotext;

    background: linear-gradient(45deg, #0004, #0000);
  }
}
</style>

// src/lib/components/Project.svelte
<script lang="ts">
	import type Project from '$lib/project';

	const from = Math.floor(Math.random() * 360);
	const to = from + Math.floor(Math.random() * 30) + 30;
	const deg = Math.floor(Math.random() * 150) + 30;

	const cssVars = `--bg-deg:${deg}deg;--bg-from:hsl(${from},80%,35%);--bg-to:hsl(${to},80%,35%);`;

	export var project: Project = {
		id: 'none',
		name: 'None',
		tags: [],
		lang: 'No lang',
		url: '.',
		description: []
	};
</script>

<div class="project" style={cssVars}>
	<a href={project.url || '.'} class="project-inner">
		<span class="lang">{project.lang}</span>
		<h1>{project.name}</h1>
		<div class="desc">
			{#each project.description as d}
				<p>{d}</p>
			{/each}
		</div>
		<ul class="tags">
			{#each project.tags as t}
				<li>{t}</li>
			{/each}
		</ul>
	</a>
</div>

<style lang="less">
	@import "../../style/constants.less";

	@color-gradient: linear-gradient(var(--bg-deg), var(--bg-from), var(--bg-to));
	@shaded: #0003;

	.project {
		padding: 0.1rem;

		height: 100%;
		width: 100%;

		background: var(--bg-from);
		background: @color-gradient;
	}

	.project-inner {
		display: grid;
		grid-template-columns: 1fr;
		grid-template-rows: repeat(2, auto) 1fr auto;

		width: 100%;
		height: 100%;

		background: transparent;
		color: var(--text);

		transition: background ease-in 200ms;

		.lang {
			grid-area: 1 / 1 / 2 / 2;

			background: var(--bg-accent);

			@media (min-width: @tablet-size) {
				background: @shaded;
			}

			font-size: 0.8rem;
			text-align: right;

			padding-right: 0.2rem;
			padding-bottom: 0.2rem;
		}

		h1 {
			grid-area: 2 / 1 / 3 / 2;

			width: 100%;
			color: var(--text);

			border-top: 1px dashed var(--text);
			border-bottom: 1px dashed var(--text);

			padding: 0;

			text-align: center;
			font-size: 1.4rem;

			transition: color ease-in 200ms;
		}

		.desc {
			grid-area: 3 / 1 / 4 / 2;

			padding: 0.2rem 0.5rem;

			background: var(--bg-accent);

			@media (min-width: @tablet-size) {
				background: @shaded;
			}

			p {
				margin: 0;
				text-align: justify;
			}
		}

		.tags {
			grid-area: 4 / 1 / 5 / 2;

			padding: 0.2rem;

			border-top: 1px dashed var(--text);

			background: var(--bg-accent);

			@media (min-width: @tablet-size) {
				background: none;
			}

			&::before {
				content: 'tags:';
				margin-right: 0.2rem;
			}

			li {
				display: inline-block;

				padding: 0 0.1rem;
				margin-right: 0.2rem;

				border: 1px solid var(--bg-from);
				border-radius: 0.25rem;

				background: @shaded;

				&:nth-child(n) {
					&::after {
						content: ',';
					}
				}

				&:nth-last-child(1) {
					&::after {
						content: '';
					}
				}
			}
		}

		&:hover {
			background: var(--bg-color);

			h1 {
				color: var(--accent);
			}

			tags {
			}
		}
	}
</style>
